export const enum Routes {
  MAIN = "/",
  REG = "/reg",
  REG_FORM = "reg_form",
  REG_CHECK_OUT = "reg_check_out",
  IDENTITY = "/identity",
  IDENTITY_FORM = "identity_form",
  IDENTITY_CHECK_OUT = "identity_check_out",
  APPLYING = "/applying",
  APPLYING_AUTO = "applying_auto",
  APPLYING_DOCS = "applying_docs",
  APPLYING_RESULT = "applying_result",
  APPLYING_SUM = "applying_sum",
  ACCOUNT = "/account",
  ACCOUNT_ID = "account_all/:id",
  ACCOUNT_ALL = "account_all",
  ACCOUNT_DOCS = "account_docs",
  ACCOUNT_LOANS = "account_loans",
  ACCOUNT_LOANS_ID = "account_loans/:id",
  ACCOUNT_PERSONAL = "account_personal",
  ACCOUNT_PERSONAL_PASSPORT = "account_personal/passport",
  ACCOUNT_PERSONAL_PTS = "account_personal/pts",
  ACCOUNT_PERSONAL_CARD = "account_personal/card",
  ACCOUNT_PROFILE = "account_profile",
  ACCOUNT_PROFILE_PHONE = "account_profile/phone",
  ACCOUNT_PROFILE_MAIL = "account_profile/mail",
}
