export const enum Routes {
  MAIN = "/",
  GET_MONEY = "/get_money",
  GM_FORM = "gm_form",
  GM_CHECK_OUT = "gm_check_out",
  IDENTITY = "/identity",
  IDENTITY_FORM = "identity_form",
  IDENTITY_CHECK_OUT = "identity_check_out",
  APPLYING = "/applying",
  APPLYING_AUTO = "applying_auto",
  APPLYING_DOCS = "applying_docs",
  APPLYING_RESULT = "applying_result",
  APPLYING_SUM = "applying_sum",
  REQUESTS = "/requests",
  REQ_ALL = "req_all",
  REQ_DOCS = "req_docs",
  REQ_LOANS = "req_loans",
  REQ_PERSONAL = "req_personal",
  REQ_PROFILE = "req_profile",
}
