export const enum Routes {
  MAIN = "/",
  REG = "/reg",
  REG_FORM = "reg_form",
  REG_CHECK_OUT = "reg_check_out",
  IDENTITY = "/identity",
  IDENTITY_FORM = "identity_form",
  IDENTITY_CHECK_OUT = "identity_check_out",
  APPLYING = "/applying",
  APPLYING_AUTO = "applying_auto",
  APPLYING_DOCS = "applying_docs",
  APPLYING_RESULT = "applying_result",
  APPLYING_SUM = "applying_sum",
  REQUESTS = "/requests",
  REQUESTS_ID = "req_all/:id",
  REQ_ALL = "req_all",
  REQ_DOCS = "req_docs",
  REQ_LOANS = "req_loans",
  REQ_LOANS_ID = "req_loans/:id",
  REQ_PERSONAL = "req_personal",
  REQ_PERSONAL_PASSPORT = "req_personal/passport",
  REQ_PERSONAL_PTS = "req_personal/pts",
  REQ_PERSONAL_CARD = "req_personal/card",
  REQ_PROFILE = "req_profile",
  REQ_PROFILE_PHONE = "req_profile/phone",
  REQ_PROFILE_MAIL = "req_profile/mail",
}
